server.port = 8080
server.servlet.context-path=/ServidorDicomFHES

spring.application.name=ServidorDicomFHES

logging.pattern.console="%date{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
logging.pattern.file="%date{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
logging.level.net.fhes = DEBUG
logging.level.org.springframework.web = INFO
logging.level.org.hibernate = INFO

# DEV
dev.urlConfiguracio = https://entitydev.fhes.cat/ConfiguracioAplicacions/config/carregarValors?idApp=3

#PRODUCCIO
produccio.urlConfiguracio = https://database.fhes.cat/ConfiguracioAplicacions/config/carregarValors?idApp=3